databases:
  - name: Budget_App_development
    databaseName: budget_app_dev
    user: caleb

services:
  - type: web
    name: mysite
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Budget_App_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
