default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: dpg-cii5ir2ip7vpelq7e4vg-a
  port: 5432
  username: caleb
  password: dpg-cii5ir2ip7vpelq7e4vg-a

development:
  <<: *default
  database: Budget_App_development

test:
  <<: *default
  database: Budget_App_test

production:
  <<: *default
  database: Budget_App_production
